<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>FcuControl</AssemblyName>
    <RootNamespace>FcuControl.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\FcuControl.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\FcuControl-icon.png" />
    <ProjectReference Include="..\FcuControl.Core\FcuControl.Core.csproj" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\THIRD-PARTY-NOTICES.md" Link="THIRD-PARTY-NOTICES.md" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
